title: Documentation
doc_version: 0.1.0
url: https://oclslam.nlamprian.me

permalink: /:categories/:title
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap
  - jemoji
  - rouge
